name: GitHub Profile Dynamic Content

on:
  schedule:
    # Updates every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch: # Allows to manually run the workflow

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Action to update the recent activity list
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "activity"
          commit_message: "chore(activity): update recent GitHub activity"
          feed_list: "https://github.com/JDIDEK.atom"
          max_post_count: 8
          template: |
            $newline - $date: $title
          date_format: "dd/mm/yyyy"

      # Action to update the quote of the day
      - uses: sinoru/actions-readme-quotes@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
